---
title: "Group 24 CA pollution burden"
author: "Van Gonzales & Meghna Rao"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(janitor)
library(here)
```

```{r}
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```

```{r, echo = FALSE, results = 'hide', fig.keep ='all'}
ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) +
  geom_hex() +
  labs(x = "% White Population", y = "CES 3.0 Score", title = "White Population Percentage v CES Pollution Burden Score (CES 3.0 Score)") +
  scale_fill_gradient(low = "coral3", high = "darkblue")
  theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5)) 
```
**Figure 1. Percentage of white population versus the CES Score.** As the percentage of the white population (x-axis) increases, the CES 3.0 Score (y-axis) gradually decreases. The greater the score, the greater the burden of pollution the population is facing.

